# Generated by Django 6.0.6 on 2026-06-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='कर्मचारी का नाम')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ईमेल आईडी')),
                ('phone', models.CharField(max_length=15, verbose_name='मोबाइल नंबर')),
                ('department', models.CharField(max_length=50, verbose_name='विभाग (Department)')),
                ('join_date', models.DateField(verbose_name='जॉइनिंग तारीख')),
            ],
        ),
    ]
