# Generated by Django 6.0.6 on 2026-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_attendance_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='month',
        ),
        migrations.AddField(
            model_name='salary',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Allowance'),
        ),
        migrations.AddField(
            model_name='salary',
            name='arrears_previous_months',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Arrears from Previous Months'),
        ),
        migrations.AddField(
            model_name='salary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bonus'),
        ),
        migrations.AddField(
            model_name='salary',
            name='client_closing_slab_comm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Client Closing Slab Comm'),
        ),
        migrations.AddField(
            model_name='salary',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission'),
        ),
        migrations.AddField(
            model_name='salary',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gross Pay'),
        ),
        migrations.AddField(
            model_name='salary',
            name='month_year',
            field=models.CharField(default='June 2026', max_length=30, verbose_name='Month & Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='net_add',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Net Add'),
        ),
        migrations.AddField(
            model_name='salary',
            name='net_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Net Deduction'),
        ),
        migrations.AddField(
            model_name='salary',
            name='paid_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10, verbose_name='Paid Status'),
        ),
        migrations.AddField(
            model_name='salary',
            name='processed_net_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Processed Net Pay'),
        ),
        migrations.AddField(
            model_name='salary',
            name='punctuality',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Punctuality'),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_net_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Net Pay'),
        ),
        migrations.AddField(
            model_name='salary',
            name='unpaid_net_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Unpaid Net Pay'),
        ),
        migrations.AddField(
            model_name='salary',
            name='work_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Work Expenses'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Basic Salary'),
        ),
    ]
